[package]
name = "ephemeral-rollups-pinocchio"
description = "Ephemeral Rollups Integration Pinocchio"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
readme = "README.md"
license = { workspace = true }
edition = { workspace = true }

[dependencies]
pinocchio = { workspace = true }
pinocchio-pubkey  = { workspace = true }
pinocchio-system  = { workspace = true }
solana-address = { version = ">=2, <3", features = ["curve25519", "serde"] }
serde = { workspace = true, default-features = false }
bincode = { version = "2.0.1", default-features = false, features = ["derive", "serde"] }

[features]
default = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(target_os, values(\"solana\"))"] }
