[package]
name = "ephemeral-rollups-pinocchio"
description = "Ephemeral Rollups Integration Pinocchio"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
readme = "README.md"
license = { workspace = true }
edition = { workspace = true }

[dependencies]
pinocchio = { workspace = true }
pinocchio-log  = { workspace = true }
pinocchio-pubkey  = { workspace = true }
pinocchio-system  = { workspace = true }
pinocchio-token  = { workspace = true }
solana-address = { version = ">=2, <3", features = ["curve25519"], optional = true }

[target.'cfg(not(any(target_os = "solana", target_arch = "bpf")))'.dependencies]
solana-pubkey = { workspace = true }

[features]
default = []
address-find-program-address = ["dep:solana-address"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(target_os, values(\"solana\"))"] }
